#-------------------------------
# Site Settings
title: Jtcarrasco
logo: '/assets/logo_header.png'
description: Jtcarrasco | Web Developer + Designer + Pet Wrangler.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Projects'
      url: '/projects/'
    # - title: 'Blog'
    #   url: '/blog/'
    - title: 'Contact'
      url: '/contact/'

#-------------------------------
# Author Settings
author:
  author__name: Jason Carrasco
  author__bio: I specialize in both visual design and coding, which allows me to tackle a wide range of projects with flexibility and creativity. I thrive on challenges that encourage learning, innovation, and the exploration of new tools and techniques to deliver exceptional results.
  #author__avatar: '/images/01-1.jpg'

social:
- {icon: "fa-brands fa-linkedin", link: "https://www.linkedin.com/in/jtcarrasco/"}
- {icon: "fa-brands fa-github", link: "https://github.com/jtcarrasco"}
- {icon: "fa-solid fa-file-pdf", link: "/assets/Jtcarrasco_resume.pdf"}
# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Hero Settings
hero:
  hero__title: I'm Jason.
  hero__description: I specialize in both visual design and coding, which allows me to tackle a wide range of projects with flexibility and creativity. I thrive on challenges that encourage learning, innovation, and the exploration of new tools and techniques to deliver exceptional results.
  #hero__image: '/images/01.jpg'


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp__input__text: Your email address...
mailchimp__button__text: Get updates


#-------------------------------
# Projects Settings
projects__settings:
  projects__title: My Recent Projects
  projects__description: 


#-------------------------------
# Testimonials Section
testimonial__title: Recommendations
testimonial__description:

testimonial__items:
  - name: "Yvonne Li"
    image: "/assets/clients/yvonne_li.webp"
    designation: "Content Marketing Supervisor"
    link: "https://www.linkedin.com/in/loveliyvonne/"
    content : "Jason is a proactive problem-solver who looks for ways to improve efficiency and long-term content management. He streamlined the nearly 50 websites our team managed, while also creating processes that made site updates easier to navigate. As a web developer, Jason focuses on ensuring everything functions as it should, with accessibility and user experience always in mind. He approaches projects with a solution-oriented mindset and consistently finds ways to make systems run more efficiently. His technical expertise and focus on functionality make him a reliable contributor to any web development team."
    
  - name: "Kristi Marquez"
    image: "/assets/clients/kristi.webp"
    designation: "Business Owner | DAS Beergarden"
    link: "https://www.linkedin.com/in/kristimarquez/"
    content : "I don't think I've ever been able to call a website redesign easy before working with Jason. He recently overhauled my company's site and the process was seamless. He listened to our goals and implemented every one of them on the first attempt, noticed potential roadblocks, and made suggestions around additional elements, plugins and SEO that have already proven their worth. His work was super fast and on-brand, which was exactly what we needed. I highly recommend Jason if you are looking for a web developer who can exceed your expectations."

  - name: "Yvonne Miller"
    image: "/assets/clients/yvonne.webp"
    designation: "Executive Vice President, Client Services | Edlio.com"
    link: "https://www.linkedin.com/in/yvonne-miller-a0639119/"
    content : "I can enthusiastically recommend Jason! He is conscientious and hardworking, always committed to solving problems creatively and working as an equal collaborator. He was always willing to jump into new projects whether they were part of his job description or not. He is committed to professional development and always learning. He would be a stellar addition to any team!"

  - name: "Anni Baghdasarian"
    image: "/assets/clients/anni.webp"
    designation: "President | Edlio.com"
    link: "https://www.linkedin.com/in/anni-baghdasarian-90905757/"
    content : "Jason is an incredible asset to any team he's on. He's willing to take on any task thrown his way and is an absolute team player. He's a fast learner, deadline driven, detail oriented and always gets his work done with a smile. I would highly recommend him to any future employer."

  - name: "Miguel Lee"
    image: "/assets/clients/miguel.webp"
    designation: "Creative Director"
    link: "https://www.linkedin.com/in/miguellee/"
    content : "Jason is extremely resourceful and has an excellent attitude/approach to his work. He played a major role in assisting us on several projects in both production and IT capacities."

  - name: "Susan Thurmond O'Neal"
    image: "/assets/clients/susan.webp"
    designation: "Operations Director"
    link: "https://www.linkedin.com/in/susantoneal/"
    content : "I miss working with Jason! He tackles every project with relentless good humor and innovation. Jason has skills that translate to many different aspects of Creative Enterprise. He will be a success wherever he goes."

  - name: "Dom Davenport"
    image: "/assets/clients/dom.webp"
    designation: "Founder & CEO Escape Studios"
    link: "https://www.linkedin.com/in/dom-davenport-7b9500a/"
    content : "Jason throws himself in to whatever task he's given and always delivers with aplomb. I would wholeheartedly recommend him to any future employer."


#-------------------------------
# Blog Section
blog__settings:
  blog__title: Recent Posts
  blog__description: 


#-------------------------------
# Gallery Footer Settings
gallery:
  gallery__images:
    - alt: 'Rest'
      url: '/assets/gallery-1.jpg'
    - alt: 'Lifestyle'
      url: '/assets/gallery-2.jpg'
    - alt: 'Hobby'
      url: '/assets/gallery-3.jpg'
    - alt: 'Notes'
      url: '/assets/gallery-4.jpg'


#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - url: '/about/'
      title: 'About'
    - url: '/contact/'
      title: 'Contact'


#-------------------------------
# Contact Settings
contact:
  form_id: info@jtcarrasco.com # Add your form_id
  description: # Add a description of your form

# NOTE
# Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id